---
title: Hide Settings Pages
description: Hides unnecessary Settings pages, which are either not recommended to use or disabled within the registry
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'SettingsPageVisibility'
    data: 'hide:crossdevice;recovery;autoplay;usb;deviceusage;maps;family-group;backup;findmydevice;privacy;privacy-speech;privacy-feedback;privacy-activityhistory;search-permissions;privacy-location;privacy-general;'
    type: REG_SZ
