---
title: Configure Quick Settings in Notification Center
description: Configures Quick Settings in Notification Center for QoL
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.ProjectL2'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.NearShare'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\QuickActionsStateCapture'
    value: 'Toggles'
    data: 'Toggles,Microsoft.QuickAction.BlueLightReduction:false,Microsoft.QuickAction.Accessibility:false,Microsoft.QuickAction.Cast:true'
    type: REG_SZ
