---
title: Services
description: Configures services
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Configuring services'}

  # Backup default Windows serivces & drivers
  - !run: {exe: 'BACKUP1.cmd', exeDir: true}

  # ------------------------ Services ------------------------

  - !run:
    exe: 'C:\Windows\AtlasDesktop\3. Configuration\1. General Configuration\Bluetooth\Disable Bluetooth.cmd'
    args: '/silent'
    option: 'disable-bluetooth'

  - !service: {name: 'AppIDSvc', operation: change, startup: 4}
  - !service: {name: 'CryptSvc', operation: change, startup: 3}
  - !service: {name: 'diagnosticshub.standardcollector.service', operation: change, startup: 4}
  - !service: {name: 'diagsvc', operation: change, startup: 4}
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
  - !service: {name: 'DispBrokerDesktopSvc', operation: change, startup: 4}
  - !service: {name: 'InstallService', operation: change, startup: 3}
  - !service: {name: 'IpxlatCfgSvc', operation: change, startup: 4}
  - !service: {name: 'KtmRm', operation: change, startup: 4}
  - !service: {name: 'luafv', operation: change, startup: 4}
  - !service: {name: 'MSDTC', operation: change, startup: 4}
  - !service: {name: 'NetTcpPortSharing', operation: change, startup: 4}
  - !service: {name: 'PcaSvc', operation: change, startup: 4}
  - !service: {name: 'PhoneSvc', operation: change, startup: 4}
  - !service: {name: 'RasMan', operation: change, startup: 4}
  - !service: {name: 'SmsRouter', operation: change, startup: 4}
  - !service: {name: 'Spooler', operation: change, startup: 4}
  - !service: {name: 'sppsvc', operation: change, startup: 3}
  - !service: {name: 'SstpSvc', operation: change, startup: 4}
  - !service: {name: 'TabletInputService', operation: change, startup: 4}
  - !service: {name: 'Themes', operation: change, startup: 4}
  - !service: {name: 'TrkWks', operation: change, startup: 4}
  - !service: {name: 'W32Time', operation: change, startup: 4}
  - !service: {name: 'WarpJITSvc', operation: change, startup: 4}
  - !service: {name: 'WdiServiceHost', operation: change, startup: 4}
  - !service: {name: 'WdiSystemHost', operation: change, startup: 4}
  - !service: {name: 'Wecsvc', operation: change, startup: 4}
  - !service: {name: 'wercplsupport', operation: change, startup: 4}
  - !service: {name: 'WerSvc', operation: change, startup: 4}
  - !service: {name: 'WEPHOSTSVC', operation: change, startup: 4}
  - !service: {name: 'WMPNetworkSvc', operation: change, startup: 4}
  - !service: {name: 'WPDBusEnum', operation: change, startup: 4}
  - !service: {name: 'WSearch', operation: change, startup: 4}
  - !service: {name: 'wuauserv', operation: change, startup: 3}
  - !service: {name: 'SEMgrSvc', operation: change, startup: 4}
  - !service: {name: 'OneSyncSvc', operation: change, startup: 4}
  # Previously deleted
  - !service: {name: 'wbengine', operation: change, startup: 4}
  - !service: {name: 'MapsBroker', operation: change, startup: 4}
  - !service: {name: 'RemoteAccess', operation: change, startup: 4}
  - !service: {name: 'RemoteRegistry', operation: change, startup: 4}
  - !service: {name: 'AJRouter', operation: change, startup: 4}
  - !service: {name: 'lfsvc', operation: change, startup: 4}
  - !service: {name: 'MessagingService', operation: change, startup: 4}
  - !service: {name: 'GraphicsPerfSvc', operation: change, startup: 4}
  - !service: {name: 'autotimesvc', operation: change, startup: 4}
  - !service: {name: 'Smartcard', operation: change, startup: 4}
  - !service: {name: 'AarSvc', operation: change, startup: 4}
  - !service: {name: 'tzautoupdate', operation: change, startup: 4}
  - !service: {name: 'PeerDistSvc', operation: change, startup: 4}
  - !service: {name: 'embeddedmode', operation: change, startup: 4}
  - !service: {name: 'fhsvc', operation: change, startup: 4}
  - !service: {name: 'wlpasvc', operation: change, startup: 4}
  - !service: {name: 'AppVClient', operation: change, startup: 4}
  # DPS 4 < breaks Data Usage
  # DsSvc 4 < can cause issues with Snip & Sketch
  # icssvc 4 < breaks mobile/Wi-Fi hotspot
  # IKEEXT 4 < causes Teredo not to work
  # DisplayEnhancementService 4 < breaks brightness slider on laptops
  # DoSvc 3 < Seems to just enable its self, probably needed in Windows 11
  # iphlpsvc 4 < causes Teredo not to work
  # KeyIso 4 < causes issues with NVCleanstall's driver telemetry tweak
  # SharedAccess 4 < breaks mobile/Wi-Fi hotspot
  # ShellHWDetection 4 < breaks bitlocker

  # ---------------------- Services END ----------------------

  # ------------------------- Drivers ------------------------

  - !service: {name: '3ware', operation: change, startup: 4}
  - !service: {name: 'ADP80XX', operation: change, startup: 4}
  - !service: {name: 'AmdK8', operation: change, startup: 4}
  - !service: {name: 'arcsas', operation: change, startup: 4}
  - !service: {name: 'AsyncMac', operation: change, startup: 4}
  - !service: {name: 'bam', operation: change, startup: 4}
  - !service: {name: 'Beep', operation: change, startup: 4}
  - !service: {name: 'bindflt', operation: change, startup: 4}
  - !service: {name: 'buttonconverter', operation: change, startup: 4}
  - !service: {name: 'CAD', operation: change, startup: 4}
  - !service: {name: 'cdfs', operation: change, startup: 4}
  - !service: {name: 'CimFS', operation: change, startup: 4}
  - !service: {name: 'circlass', operation: change, startup: 4}
  - !service: {name: 'cnghwassist', operation: change, startup: 4}
  - !service: {name: 'CompositeBus', operation: change, startup: 4}
  - !service: {name: 'Dfsc', operation: change, startup: 4}
  - !service: {name: 'ErrDev', operation: change, startup: 4}
  - !service: {name: 'fdc', operation: change, startup: 4}
  - !service: {name: 'flpydisk', operation: change, startup: 4}
  - !service: {name: 'GpuEnergyDrv', operation: change, startup: 4}
  - !service: {name: 'nvraid', operation: change, startup: 4}
  - !service: {name: 'sfloppy', operation: change, startup: 4}
  - !service: {name: 'SiSRaid2', operation: change, startup: 4}
  - !service: {name: 'SiSRaid4', operation: change, startup: 4}
  - !service: {name: 'tcpipreg', operation: change, startup: 4}
  - !service: {name: 'Telemetry', operation: change, startup: 4}
  - !service: {name: 'udfs', operation: change, startup: 4}
  - !service: {name: 'VerifierExt', operation: change, startup: 4}
  - !service: {name: 'vsmraid', operation: change, startup: 4}
  - !service: {name: 'VSTXRAID', operation: change, startup: 4}
  - !service: {name: 'wcnfs', operation: change, startup: 4}
  - !service: {name: 'WindowsTrustedRTProxy', operation: change, startup: 4}
  # rdbss 3 < Commented as we're not sure if it functions normally set to manual
  # FileInfo 4 < Breaks installing Microsoft Store applications to different disk
  # FileCrypt 4 < Breaks installing Microsoft Store applications to different disk
  # PEAUTH 4 < breaks UWP streaming applications such as netflix, manual mode does not fix
  # NdisVirtualBus 4 < breaks network bridges
  # umbus 4 < breaks Hyper-V Enhanced Session
  # volmgrx 4 < breaks dynamic disks
  # wcifs 4 < breaks various Microsoft Store games, erroring with "filter not found"
  
  # ----------------------- Drivers END ----------------------
